# Generated by Django 5.0.3 on 2024-03-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('numTelephone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('client', 'Client'), ('moderateur', 'Moderateur')], max_length=20)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('dateNaiss', models.DateField()),
                ('lieuNaiss', models.CharField(max_length=255)),
                ('univer_Entrep', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
            ],
        ),
    ]
