# Generated by Django 5.0.3 on 2024-05-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('moderateur', 'Moderateur'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
