# Generated by Django 5.0.3 on 2024-04-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripeCustomerId',
            field=models.CharField(default='non', max_length=30),
            preserve_default=False,
        ),
    ]
