# Generated by Django 5.0.3 on 2024-06-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='warned',
            field=models.BooleanField(default=False),
        ),
    ]
