# Generated by Django 5.0.3 on 2024-06-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_customuser_warned'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='etat',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
