# Generated by Django 5.0.3 on 2024-05-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='etat',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
