# Generated by Django 5.0.2 on 2024-05-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomaineInteret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_domaine', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='domaines_interet',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', to='User.domaineinteret'),
        ),
    ]
