# Generated by Django 5.0.3 on 2024-05-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_customuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntrestDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='domaines_interet',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs', to='User.intrestdomain'),
        ),
    ]
