# Generated by Django 5.0.3 on 2024-05-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administartion', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
