POST http://127.0.0.1:9000/login 
Content-Type: application/json

{ "username": "adam5", "password": "Pass1234!" }

###

POST http://127.0.0.1:9000/signup 
Content-Type: application/json

{ "username": "adam5", "password": "Pass1234!", "email": "adam@mail.com" }

###

GET http://127.0.0.1:9000/test_token 
Content-Type: application/json
Authorization: token cbd44d27f6493862e1e7386e78c1ee97e8617a81