# Generated by Django 5.0.3 on 2024-03-22 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JuridicalText',
            fields=[
                ('id_text', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type_text', models.CharField(max_length=100)),
                ('signature_date', models.DateField()),
                ('publication_date', models.DateField()),
                ('jt_number', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('official_journal_number', models.IntegerField()),
                ('official_journal_year', models.IntegerField()),
                ('official_journal_page', models.IntegerField()),
                ('description', models.TextField()),
                ('text_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('text_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddConstraint(
            model_name='officialjournal',
            constraint=models.UniqueConstraint(fields=('number', 'year'), name='unique_official_journal'),
        ),
        migrations.AddField(
            model_name='juridicaltext',
            name='official_journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='juridical_texts', to='Data_Collection.officialjournal'),
        ),
    ]
