# Generated by Django 5.0.3 on 2024-05-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjutstement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjusted_num', models.CharField(max_length=100)),
                ('adjusting_num', models.CharField(max_length=100)),
                ('adjustment_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='juridicaltext',
            name='official_journal_number',
        ),
        migrations.RemoveField(
            model_name='juridicaltext',
            name='official_journal_year',
        ),
        migrations.AddField(
            model_name='juridicaltext',
            name='extracted_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='juridicaltext',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='juridicaltext',
            name='jt_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='juridicaltext',
            name='publication_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='juridicaltext',
            name='signature_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='juridicaltext',
            name='source',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='juridicaltext',
            name='text_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
