# Generated by Django 5.0.3 on 2024-04-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Collection', '0003_alter_adjutstement_adjusted_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juridicaltext',
            name='extracted_text',
            field=models.TextField(null=True),
        ),
    ]
