# Generated by Django 5.0.3 on 2024-05-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Collection', '0003_intrestdomain_juridicaltext_intrest_scrapping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juridicaltext',
            name='intrest',
        ),
        migrations.RemoveField(
            model_name='scrapping',
            name='user',
        ),
        migrations.RemoveField(
            model_name='juridicaltext',
            name='scrapping',
        ),
        migrations.DeleteModel(
            name='IntrestDomain',
        ),
        migrations.DeleteModel(
            name='Scrapping',
        ),
    ]
