# Generated by Django 5.0.3 on 2024-05-19 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Collection', '0004_juridicaltext_extracted_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntrestDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='juridicaltext',
            name='intrest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Data_Collection.intrestdomain'),
        ),
        migrations.CreateModel(
            name='Scrapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='juridicaltext',
            name='scrapping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Data_Collection.scrapping'),
        ),
    ]
