# Generated by Django 5.0.3 on 2024-05-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Collection', '0005_intrestdomain_juridicaltext_intrest_scrapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapping',
            name='state',
            field=models.CharField(choices=[('failed', 'Failed'), ('success', 'Success')], default='failed', max_length=20),
        ),
    ]
