# Generated by Django 5.0.3 on 2024-05-19 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Collection', '0005_intrestdomain_juridicaltext_intrest_scrapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapping',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
