# Generated by Django 5.0.2 on 2024-05-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Collection', '0006_scrapping_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapping',
            name='state',
            field=models.CharField(choices=[('failed', 'Failed'), ('success', 'Success'), ('loading', 'Loading')], default='failed', max_length=20),
        ),
    ]
