# Generated by Django 5.0.3 on 2024-05-28 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Collection', '0006_scrapping_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapping',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 28), null=True),
        ),
        migrations.AlterField(
            model_name='scrapping',
            name='state',
            field=models.CharField(choices=[('failed', 'Failed'), ('success', 'Success'), ('loading', 'Loading')], default='failed', max_length=20),
        ),
    ]
