# Generated by Django 5.0.3 on 2024-05-28 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data_Collection', '0007_alter_scrapping_state'),
        ('User', '0004_intrestdomain_customuser_domaines_interet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juridicaltext',
            name='intrest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.intrestdomain'),
        ),
        migrations.DeleteModel(
            name='IntrestDomain',
        ),
    ]
