# Generated by Django 5.0.3 on 2024-04-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payement_Validation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='montant_restant',
        ),
        migrations.AddField(
            model_name='facture',
            name='payé',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
