# Generated by Django 5.0.3 on 2024-04-04 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payement_Validation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='stripeId',
            field=models.CharField(default="none", max_length=20),
            preserve_default=False,
        ),
    ]
