# Generated by Django 5.0.3 on 2024-04-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payement_Validation', '0003_remove_service_stripeid_alter_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='priceId',
            field=models.CharField(default='price_1OygzALDzFR9kcMzRSTnrTUn', max_length=30),
            preserve_default=False,
        ),
    ]
