# Generated by Django 5.0.3 on 2024-04-23 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payement_Validation', '0003_access_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abonnement',
            old_name='id',
            new_name='SubId',
        ),
    ]
