# Generated by Django 5.0.3 on 2024-04-04 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payement_Validation', '0004_service_priceid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('montant', models.FloatField()),
                ('montant_payé', models.FloatField()),
                ('montant_restant', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='facture',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Payement_Validation.facture'),
        ),
    ]
