# Generated by Django 5.0.3 on 2024-04-09 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payement_Validation', '0005_facture_alter_service_id_abonnement_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payement_Validation.service'),
        ),
    ]
