# Generated by Django 5.0.3 on 2024-04-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payement_Validation', '0006_alter_abonnement_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='accesses',
            field=models.ManyToManyField(to='Payement_Validation.access'),
        ),
    ]
