# Generated by Django 5.0.3 on 2024-04-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payement_Validation', '0007_access_service_accesses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='name',
            new_name='nom',
        ),
    ]
