# Generated by Django 5.0.3 on 2024-04-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payement_Validation', '0008_rename_name_access_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='pdf',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
