# Generated by Django 5.0.3 on 2024-04-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payement_Validation', '0009_facture_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='methode_de_payment',
            field=models.CharField(default='CIB', max_length=20),
            preserve_default=False,
        ),
    ]
