# Generated by Django 5.0.3 on 2024-04-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payement_Validation', '0010_facture_methode_de_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='methode_de_payment',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
